import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
//Next JS
import Link from 'next/link';
//Material UI Fonts
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
//Material UI components
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { AppBar, Box, Container, Toolbar, IconButton, Typography, InputBase } from '@mui/material';
import Navbar from 'src/components/Navbar';
import List from 'src/components/List';

// const theme = createTheme({
//   // palette: {
//   //   primary: {

//   //   }
//   // }
// })

export default function Home() {
  return (
    <>
      <Head>
        <title>HotelGuru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Container sx={{
        height: "100vh",
        '& .MuiContainer-root': {
          padding: "0px 0px",
        }
        }}>
        <List />
      </Container> */}
    </>
  )
}
