import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
//Next JS
import Link from 'next/link';
//Material UI Fonts
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
//Material UI components
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { AppBar, Box, Container, Toolbar, IconButton, Typography, InputBase } from '@mui/material';
import AppBarSearch from '/Users/masonisblue/Hackreactor/rfp2302-mvp/hotel-guru/src/AppBarSearch.tsx';
import List from '/Users/masonisblue/Hackreactor/rfp2302-mvp/hotel-guru/src/List.tsx';

const theme = createTheme({
  // palette: {
  //   primary: {

  //   }
  // }
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBarSearch />
      <Container sx={{
        height: "100vh",
        '& .MuiContainer-root': {
          padding: "0px 0px",
        }
        }}>
        <List />
      </Container>
    </>
  )
}
